#ifndef crypto_kem_H
#define crypto_kem_H

#include "crypto_kem_ntrulpr857.h"

#define crypto_kem_keypair crypto_kem_ntrulpr857_keypair
#define crypto_kem_enc crypto_kem_ntrulpr857_enc
#define crypto_kem_dec crypto_kem_ntrulpr857_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_ntrulpr857_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_ntrulpr857_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_ntrulpr857_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_ntrulpr857_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "ntrulpr857"

#endif
