#!/bin/sh
gcc -O3 -march=native -mtune=native -Wall -I. -Isubroutines -DKAT -DKATNUM=`cat KATNUM` "-DCRYPTO_NAMESPACE(x)=x" -o kat nist/kat_kem.c nist/rng.c Decode.c Encode.c int32.c kem.c uint32.c     subroutines/crypto_hash_sha512.c subroutines/crypto_sort_uint32.c subroutines/crypto_stream_aes256ctr.c  -lcrypto -ldl 
