#ifndef crypto_kem_H
#define crypto_kem_H

#include "crypto_kem_sntrup953.h"

#define crypto_kem_keypair crypto_kem_sntrup953_keypair
#define crypto_kem_enc crypto_kem_sntrup953_enc
#define crypto_kem_dec crypto_kem_sntrup953_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_sntrup953_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_sntrup953_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_sntrup953_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_sntrup953_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "sntrup953"

#endif
