#ifndef crypto_kem_H
#define crypto_kem_H

#include "crypto_kem_sntrup653.h"

#define crypto_kem_keypair crypto_kem_sntrup653_keypair
#define crypto_kem_enc crypto_kem_sntrup653_enc
#define crypto_kem_dec crypto_kem_sntrup653_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_sntrup653_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_sntrup653_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_sntrup653_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_sntrup653_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "sntrup653"

#endif
