#ifndef crypto_kem_H
#define crypto_kem_H

#include "crypto_kem_sntrup1277.h"

#define crypto_kem_keypair crypto_kem_sntrup1277_keypair
#define crypto_kem_enc crypto_kem_sntrup1277_enc
#define crypto_kem_dec crypto_kem_sntrup1277_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_sntrup1277_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_sntrup1277_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_sntrup1277_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_sntrup1277_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "sntrup1277"

#endif
